// <auto-generated />
using System;
using EFMRN2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFMRN2.Migrations
{
    [DbContext(typeof(EFMRN2Context))]
    [Migration("20220125212802_TileUpdate")]
    partial class TileUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EFMRN2.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("EFMRN2.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Bearing")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Transparency")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EFMRN2.Models.Tile", b =>
                {
                    b.Property<int>("TileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Aux")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<string>("Texture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Transparent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.HasKey("TileId");

                    b.ToTable("Map");

                    b.HasData(
                        new
                        {
                            TileId = 1,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 13,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 25,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 37,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 4,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 49,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 5,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 61,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 6,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 73,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 7,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 85,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 8,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 97,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 9,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 109,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 121,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 11,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 133,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 0,
                            Z = 0
                        },
                        new
                        {
                            TileId = 2,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 14,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 26,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 38,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 4,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 50,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 5,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 62,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 6,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 74,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 7,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 86,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 8,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 98,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 9,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 110,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 122,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 11,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 134,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 1,
                            Z = 0
                        },
                        new
                        {
                            TileId = 3,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 15,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 27,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 39,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 4,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 51,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 5,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 63,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 6,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 75,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 7,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 87,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 8,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 99,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 9,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 111,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 123,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 11,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 135,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 2,
                            Z = 0
                        },
                        new
                        {
                            TileId = 4,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 16,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 28,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 40,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 4,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 52,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 5,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 64,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 6,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 76,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 7,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 88,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 8,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 100,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 9,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 112,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 124,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 11,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 136,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 3,
                            Z = 0
                        },
                        new
                        {
                            TileId = 5,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 17,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 29,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 41,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 4,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 53,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 5,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 65,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 6,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 77,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 7,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 89,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 8,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 101,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 9,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 113,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 125,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 11,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 137,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 4,
                            Z = 0
                        },
                        new
                        {
                            TileId = 6,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 18,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 30,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 42,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 4,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 54,
                            Aux = "0",
                            Method = 0,
                            Texture = "void",
                            Transparent = false,
                            X = 5,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 66,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 6,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 78,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 7,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 90,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 8,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 102,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 9,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 114,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 126,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 11,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 138,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 5,
                            Z = 0
                        },
                        new
                        {
                            TileId = 7,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 19,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 31,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 43,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 4,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 55,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 5,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 67,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 6,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 79,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 7,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 91,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 8,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 103,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 9,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 115,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 127,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 11,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 139,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 6,
                            Z = 0
                        },
                        new
                        {
                            TileId = 8,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 20,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 32,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 44,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 4,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 56,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 5,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 68,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 6,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 80,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 7,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 92,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 8,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 104,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 9,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 116,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 128,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 11,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 140,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 7,
                            Z = 0
                        },
                        new
                        {
                            TileId = 9,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 21,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 33,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 45,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 4,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 57,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 5,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 69,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 6,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 81,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 7,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 93,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 8,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 105,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 9,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 117,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 129,
                            Aux = "0",
                            Method = 0,
                            Texture = "floor",
                            Transparent = true,
                            X = 11,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 141,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 8,
                            Z = 0
                        },
                        new
                        {
                            TileId = 10,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 22,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 34,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 46,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 4,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 58,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 5,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 70,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 6,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 82,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 7,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 94,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 8,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 106,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 9,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 118,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 130,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 11,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 142,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 9,
                            Z = 0
                        },
                        new
                        {
                            TileId = 11,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 23,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 35,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 47,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 4,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 59,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 5,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 71,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 6,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 83,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 7,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 95,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 8,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 107,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 9,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 119,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 131,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 11,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 143,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 10,
                            Z = 0
                        },
                        new
                        {
                            TileId = 12,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 0,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 24,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 1,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 36,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 3,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 48,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 4,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 60,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 5,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 72,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 6,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 84,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 7,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 96,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 8,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 108,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 9,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 120,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 10,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 132,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 11,
                            Y = 11,
                            Z = 0
                        },
                        new
                        {
                            TileId = 144,
                            Aux = "0",
                            Method = 0,
                            Texture = "wall",
                            Transparent = false,
                            X = 12,
                            Y = 11,
                            Z = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EFMRN2.Models.Player", b =>
                {
                    b.HasOne("EFMRN2.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EFMRN2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EFMRN2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFMRN2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EFMRN2.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
