using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace EFMRN2.Models
{
  public class EFMRN2Context : IdentityDbContext<ApplicationUser>
  {
    public DbSet<Tile> Map {get;set;}
    public DbSet<Player> Players { get; set; }
    public DbSet<ApplicationUser> GameUsers {get;set;}
    public EFMRN2Context(DbContextOptions options) : base(options) {}
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
    protected override void OnModelCreating(ModelBuilder builder)
    {
      base.OnModelCreating(builder);
      builder.Entity<Tile>().HasData(
        new Tile { TileId = 1, X = 0, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 13, X = 1, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 25, X = 3, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 37, X = 4, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 49, X = 5, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 61, X = 6, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 73, X = 7, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 85, X = 8, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 97, X = 9, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 109, X = 10, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 121, X = 11, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 133, X = 12, Y = 0, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 2, X = 0, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 14, X = 1, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 26, X = 3, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 38, X = 4, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 50, X = 5, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 62, X = 6, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 74, X = 7, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 86, X = 8, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 98, X = 9, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 110, X = 10, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 122, X = 11, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 134, X = 12, Y = 1, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 3, X = 0, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 15, X = 1, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 27, X = 3, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 39, X = 4, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 51, X = 5, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 63, X = 6, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 75, X = 7, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 87, X = 8, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 99, X = 9, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 111, X = 10, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 123, X = 11, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 135, X = 12, Y = 2, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 4, X = 0, Y = 3, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 16, X = 1, Y = 3, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 28, X = 3, Y = 3, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 40, X = 4, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 52, X = 5, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 64, X = 6, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 76, X = 7, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 88, X = 8, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 100, X = 9, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 112, X = 10, Y = 3, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 124, X = 11, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 136, X = 12, Y = 3, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 5, X = 0, Y = 4, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 17, X = 1, Y = 4, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 29, X = 3, Y = 4, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 41, X = 4, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 53, X = 5, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 65, X = 6, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 77, X = 7, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 89, X = 8, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 101, X = 9, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 113, X = 10, Y = 4, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 125, X = 11, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 137, X = 12, Y = 4, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 6, X = 0, Y = 5, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 18, X = 1, Y = 5, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 30, X = 3, Y = 5, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 42, X = 4, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 54, X = 5, Y = 5, Z = 0, Transparent = false, Texture = "void", Aux = "0", Method = 0 }, new Tile { TileId = 66, X = 6, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 78, X = 7, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 90, X = 8, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 102, X = 9, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 114, X = 10, Y = 5, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 126, X = 11, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 138, X = 12, Y = 5, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 7, X = 0, Y = 6, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 19, X = 1, Y = 6, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 31, X = 3, Y = 6, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 43, X = 4, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 55, X = 5, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 67, X = 6, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 79, X = 7, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 91, X = 8, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 103, X = 9, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 115, X = 10, Y = 6, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 127, X = 11, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 139, X = 12, Y = 6, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 8, X = 0, Y = 7, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 20, X = 1, Y = 7, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 32, X = 3, Y = 7, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 44, X = 4, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 56, X = 5, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 68, X = 6, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 80, X = 7, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 92, X = 8, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 104, X = 9, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 116, X = 10, Y = 7, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 128, X = 11, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 140, X = 12, Y = 7, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 9, X = 0, Y = 8, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 21, X = 1, Y = 8, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 33, X = 3, Y = 8, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 45, X = 4, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 57, X = 5, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 69, X = 6, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 81, X = 7, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 93, X = 8, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 105, X = 9, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 117, X = 10, Y = 8, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 129, X = 11, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 }, new Tile { TileId = 141, X = 12, Y = 8, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 10, X = 0, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 22, X = 1, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 34, X = 3, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 46, X = 4, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 58, X = 5, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 70, X = 6, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 82, X = 7, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 94, X = 8, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 106, X = 9, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 118, X = 10, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 130, X = 11, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 142, X = 12, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 11, X = 0, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 23, X = 1, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 35, X = 3, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 47, X = 4, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 59, X = 5, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 71, X = 6, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 83, X = 7, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 95, X = 8, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 107, X = 9, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 119, X = 10, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 131, X = 11, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 143, X = 12, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 12, X = 0, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 24, X = 1, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 36, X = 3, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 48, X = 4, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 60, X = 5, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 72, X = 6, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 84, X = 7, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 96, X = 8, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 108, X = 9, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 120, X = 10, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 132, X = 11, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }, new Tile { TileId = 144, X = 12, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 145, X = 2, Y = 0, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 146, X = 2, Y = 1, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 147, X = 2, Y = 2, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 148, X = 2, Y = 3, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 149, X = 2, Y = 4, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 150, X = 2, Y = 5, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 151, X = 2, Y = 6, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 152, X = 2, Y = 7, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 153, X = 2, Y = 8, Z = 0, Transparent = true, Texture = "floor", Aux = "0", Method = 0 },
        new Tile { TileId = 154, X = 2, Y = 9, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 155, X = 2, Y = 10, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 },
        new Tile { TileId = 156, X = 2, Y = 11, Z = 0, Transparent = false, Texture = "wall", Aux = "0", Method = 0 }
      );
    }
  }
}